import type { Recipe } from "@/types";

export const LUNCH_RECIPES: Recipe[] = [
  {
    id: "l1",
    title: "Avocado-Toast mit Rührei",
    description: "Cremige Avocado auf knusprigem Toast, gekrönt mit fluffigem Rührei und frischen Kräutern.",
    category: "lunch",
    tags: ["Quick & Easy", "Vegetarisch", "Proteinreich"],
    prepTime: 10,
    servings: 2,
    emoji: "🥑",
    calories: 380,
    protein: 18,
    ingredients: [
      "2 Scheiben Vollkornbrot",
      "1 reife Avocado",
      "3 Eier",
      "Salz, Pfeffer",
      "Chiliflocken",
      "Frischer Schnittlauch",
      "1 TL Butter",
      "Zitronensaft",
    ],
    steps: [
      "Brot toasten bis es goldbraun ist.",
      "Avocado halbieren, entkernen und das Fruchtfleisch mit einer Gabel zerdrücken.",
      "Avocadomasse mit Zitronensaft, Salz und Pfeffer würzen.",
      "Eier in einer Schüssel verquirlen, in Butter bei mittlerer Hitze cremig rühren.",
      "Avocado auf den Toast streichen, Rührei darauf verteilen.",
      "Mit Chiliflocken und Schnittlauch garnieren.",
    ],
  },
  {
    id: "l2",
    title: "Caprese-Bowl mit Pesto",
    description: "Frische Tomaten, Mozzarella und Basilikum in Rekordzeit – mediterrane Leichtigkeit.",
    category: "lunch",
    tags: ["Quick & Easy", "Vegetarisch", "No-Cook"],
    prepTime: 8,
    servings: 2,
    emoji: "🍅",
    calories: 320,
    protein: 16,
    ingredients: [
      "250 g Kirschtomaten",
      "200 g Büffelmozzarella",
      "Frisches Basilikum",
      "3 EL Pesto (grün)",
      "Olivenöl extra vergine",
      "Balsamico-Reduktion",
      "Salz, Pfeffer",
    ],
    steps: [
      "Kirschtomaten halbieren, Mozzarella in Stücke reißen.",
      "Alles in einer Schüssel anrichten.",
      "Pesto darüber verteilen.",
      "Mit Olivenöl und Balsamico beträufeln.",
      "Mit frischem Basilikum und Meersalz abschmecken.",
    ],
  },
  {
    id: "l3",
    title: "Griechischer Wraps mit Tzatziki",
    description: "Knackiges Gemüse, Feta und selbstgemachtes Tzatziki in einem weichen Wrap.",
    category: "lunch",
    tags: ["Quick & Easy", "Vegetarisch"],
    prepTime: 15,
    servings: 2,
    emoji: "🌯",
    calories: 410,
    protein: 15,
    ingredients: [
      "2 Tortilla-Wraps",
      "150 g Feta",
      "1 Gurke",
      "10 Oliven",
      "2 EL Tzatziki",
      "1 Tomate",
      "Frischer Dill",
      "Rote Zwiebel",
    ],
    steps: [
      "Gurke, Tomate und Zwiebel würfeln.",
      "Feta krümeln.",
      "Wraps kurz in einer Pfanne oder Mikrowelle erwärmen.",
      "Tzatziki auf den Wraps verstreichen.",
      "Gemüse, Feta und Oliven darauf verteilen.",
      "Mit Dill bestreuen, fest einrollen und diagonal schneiden.",
    ],
  },
  {
    id: "l4",
    title: "Spinat-Feta-Omelette",
    description: "Fluffiges Omelette prall gefüllt mit Babyspinat und cremigem Feta.",
    category: "lunch",
    tags: ["Quick & Easy", "Vegetarisch", "Glutenfrei", "Low-Carb"],
    prepTime: 12,
    servings: 2,
    emoji: "🍳",
    calories: 290,
    protein: 22,
    ingredients: [
      "4 Eier",
      "80 g Babyspinat",
      "80 g Feta",
      "1 Knoblauchzehe",
      "Olivenöl",
      "Salz, Pfeffer",
      "Muskatnuss",
    ],
    steps: [
      "Eier verquirlen, mit Salz und Pfeffer würzen.",
      "Spinat und Knoblauch in Olivenöl kurz andünsten.",
      "Ei-Masse in die Pfanne geben, bei mittlerer Hitze stocken lassen.",
      "Feta und Spinat auf eine Hälfte verteilen.",
      "Omelette zusammenklappen und servieren.",
    ],
  },
  {
    id: "l5",
    title: "Hummus-Gemüse-Bowl",
    description: "Buntes Gemüse auf cremigem Hummus – schnell, sättigend und voll von Vitaminen.",
    category: "lunch",
    tags: ["Quick & Easy", "Vegetarisch", "Vegan", "Glutenfrei"],
    prepTime: 10,
    servings: 2,
    emoji: "🥙",
    calories: 350,
    protein: 12,
    ingredients: [
      "200 g fertiger Hummus",
      "1 Paprika",
      "1 Gurke",
      "10 Kirschtomaten",
      "2 Möhren",
      "Pita-Brot oder Cracker",
      "Paprikapulver",
      "Olivenöl",
      "Sesam",
    ],
    steps: [
      "Gemüse waschen und in Streifen/Scheiben schneiden.",
      "Hummus auf zwei Schüsseln verteilen.",
      "Gemüse dekorativ darauf anrichten.",
      "Mit Olivenöl, Paprikapulver und Sesam toppen.",
      "Mit Pita-Brot servieren.",
    ],
  },
  {
    id: "l6",
    title: "Tomatensuppe mit Croutons",
    description: "Samtweiche Tomatensuppe aus passierten Tomaten, fertig in unter 20 Minuten.",
    category: "lunch",
    tags: ["Quick & Easy", "Vegetarisch", "Vegan"],
    prepTime: 18,
    servings: 4,
    emoji: "🍲",
    calories: 240,
    protein: 6,
    ingredients: [
      "2 Dosen (800 g) gehackte Tomaten",
      "1 Zwiebel",
      "2 Knoblauchzehen",
      "400 ml Gemüsebrühe",
      "Olivenöl",
      "1 TL Zucker",
      "Basilikum",
      "Brot für Croutons",
    ],
    steps: [
      "Zwiebel und Knoblauch in Olivenöl glasig dünsten.",
      "Tomaten und Brühe zugeben, 10 Minuten köcheln.",
      "Suppe mit dem Stabmixer pürieren.",
      "Mit Salz, Zucker und Basilikum abschmecken.",
      "Brot in Würfel schneiden, in Olivenöl knusprig braten.",
      "Suppe mit Croutons und Basilikum servieren.",
    ],
  },
  {
    id: "l7",
    title: "Pasta Aglio e Olio",
    description: "Klassiker der italienischen Küche – nur 5 Zutaten, fertig in 15 Minuten.",
    category: "lunch",
    tags: ["Quick & Easy", "Vegetarisch", "Klassiker"],
    prepTime: 15,
    servings: 2,
    emoji: "🍝",
    calories: 450,
    protein: 13,
    ingredients: [
      "200 g Spaghetti",
      "4 Knoblauchzehen",
      "6 EL Olivenöl",
      "Chiliflocken",
      "Frische Petersilie",
      "Salz",
      "Parmesan (optional)",
    ],
    steps: [
      "Spaghetti al dente kochen, 1 Tasse Nudelwasser aufheben.",
      "Knoblauch in dünne Scheiben schneiden.",
      "Knoblauch in Olivenöl bei niedriger Hitze goldgelb braten.",
      "Chiliflocken zugeben, Pasta in die Pfanne geben.",
      "Etwas Nudelwasser zugeben und schwenken.",
      "Mit Petersilie und Parmesan servieren.",
    ],
  },
  {
    id: "l8",
    title: "Quesadillas mit schwarzen Bohnen",
    description: "Knusprige Tortillas gefüllt mit Käse, schwarzen Bohnen und Avocado.",
    category: "lunch",
    tags: ["Quick & Easy", "Vegetarisch"],
    prepTime: 15,
    servings: 2,
    emoji: "🫔",
    calories: 480,
    protein: 20,
    ingredients: [
      "4 Tortilla-Wraps",
      "1 Dose schwarze Bohnen",
      "150 g Cheddar gerieben",
      "1 Avocado",
      "Saure Sahne",
      "Salsa",
      "Koriander",
    ],
    steps: [
      "Bohnen abgießen und würzen.",
      "Käse auf zwei Wraps verteilen, Bohnen darauf.",
      "Mit dem zweiten Wrap bedecken.",
      "In einer Pfanne ohne Fett von beiden Seiten golden braten.",
      "In Dreiecke schneiden.",
      "Mit Avocado, saurer Sahne und Salsa servieren.",
    ],
  },
  {
    id: "l9",
    title: "Mango-Halloumi-Salat",
    description: "Gebratener Halloumi trifft süße Mango und frische Minze – Sommerfeeling pur.",
    category: "lunch",
    tags: ["Quick & Easy", "Vegetarisch", "Glutenfrei"],
    prepTime: 15,
    servings: 2,
    emoji: "🥗",
    calories: 390,
    protein: 19,
    ingredients: [
      "200 g Halloumi",
      "1 reife Mango",
      "100 g Rucola",
      "Frische Minze",
      "Limettensaft",
      "Olivenöl",
      "1 EL Honig",
    ],
    steps: [
      "Halloumi in Scheiben schneiden und in einer heißen Pfanne ohne Öl goldbraun braten.",
      "Mango schälen und würfeln.",
      "Dressing aus Limettensaft, Olivenöl und Honig mischen.",
      "Rucola, Mango und Halloumi anrichten.",
      "Dressing darüber, mit Minze garnieren.",
    ],
  },
  {
    id: "l10",
    title: "Zucchini-Minz-Suppe",
    description: "Leichte, cremige Suppe mit frischer Minze – ideal für heiße Tage.",
    category: "lunch",
    tags: ["Quick & Easy", "Vegetarisch", "Low-Carb", "Vegan"],
    prepTime: 20,
    servings: 4,
    emoji: "🥣",
    calories: 180,
    protein: 5,
    ingredients: [
      "3 Zucchini",
      "1 Zwiebel",
      "500 ml Gemüsebrühe",
      "Frische Minze",
      "Olivenöl",
      "Salz, Pfeffer",
      "Zitronensaft",
    ],
    steps: [
      "Zwiebel würfeln und in Olivenöl andünsten.",
      "Zucchini in Stücke schneiden und zugeben.",
      "Mit Brühe aufgießen, 10 Minuten köcheln.",
      "Mit Stabmixer fein pürieren.",
      "Minze zugeben, nochmal pürieren.",
      "Mit Zitronensaft abschmecken.",
    ],
  },
  {
    id: "l11",
    title: "Bruschetta Trio",
    description: "Drei klassische Toppings auf knusprigem Ciabatta – schnell und beeindruckend.",
    category: "lunch",
    tags: ["Quick & Easy", "Vegetarisch"],
    prepTime: 12,
    servings: 2,
    emoji: "🍞",
    calories: 350,
    protein: 11,
    ingredients: [
      "½ Ciabatta",
      "3 Tomaten",
      "Basilikum",
      "Knoblauch",
      "Ricotta",
      "Olivenöl",
      "Meersalz",
    ],
    steps: [
      "Ciabatta in Scheiben schneiden und toasten.",
      "Scheiben mit einer angeschnittenen Knoblauchzehe einreiben.",
      "Tomaten würfeln, mit Olivenöl und Basilikum mischen.",
      "Tomatenmix auf Bruschetta #1 geben.",
      "Ricotta mit Olivenöl und Salz auf Bruschetta #2.",
      "Kombination aus beidem auf Bruschetta #3.",
    ],
  },
  {
    id: "l12",
    title: "Birne-Gorgonzola-Salat",
    description: "Eleganter Salat mit karamellisierter Birne, Walnüssen und Gorgonzola.",
    category: "lunch",
    tags: ["Quick & Easy", "Vegetarisch", "Glutenfrei"],
    prepTime: 12,
    servings: 2,
    emoji: "🥗",
    calories: 370,
    protein: 12,
    ingredients: [
      "2 Birnen",
      "80 g Gorgonzola",
      "50 g Walnüsse",
      "100 g gemischter Salat",
      "2 EL Honig",
      "1 EL Butter",
      "Balsamico",
    ],
    steps: [
      "Birnen vierteln, in Butter mit Honig karamellisieren.",
      "Walnüsse kurz in der trockenen Pfanne rösten.",
      "Salatdressing aus Balsamico und Olivenöl mischen.",
      "Salat auf Tellern anrichten.",
      "Birnen, Gorgonzola und Walnüsse darüber verteilen.",
    ],
  },
];

export const DINNER_RECIPES: Recipe[] = [
  {
    id: "d1",
    title: "Tofu-Brokkoli-Pfanne mit Erdnusssauce",
    description: "Knuspriger Tofu und bissfester Brokkoli in einer cremigen Erdnuss-Sojasauce.",
    category: "dinner",
    tags: ["Low-Carb", "High-Protein", "Vegan", "Glutenfrei"],
    prepTime: 25,
    servings: 2,
    emoji: "🥦",
    calories: 380,
    protein: 28,
    ingredients: [
      "400 g fester Tofu",
      "300 g Brokkoli",
      "3 EL Erdnussmus",
      "2 EL Sojasoße",
      "1 EL Sesamöl",
      "Knoblauch, Ingwer",
      "Sesam, Frühlingszwiebeln",
      "Chilisauce",
    ],
    steps: [
      "Tofu pressen, in Würfel schneiden und in Öl von allen Seiten knusprig braten.",
      "Brokkoli in Röschen teilen, 3 Minuten blanchieren.",
      "Erdnusssauce: Erdnussmus, Sojasoße, Sesamöl, Knoblauch und etwas Wasser mischen.",
      "Tofu und Brokkoli in der Pfanne zusammen erhitzen.",
      "Sauce zugeben und gut durchschwenken.",
      "Mit Sesam und Frühlingszwiebeln servieren.",
    ],
  },
  {
    id: "d2",
    title: "Blumenkohl-Curry mit Kichererbsen",
    description: "Aromatisches indisches Curry mit Blumenkohl und Kichererbsen, reich an Proteinen.",
    category: "dinner",
    tags: ["Low-Carb", "High-Protein", "Vegan", "Glutenfrei"],
    prepTime: 30,
    servings: 4,
    emoji: "🍛",
    calories: 320,
    protein: 16,
    ingredients: [
      "1 Blumenkohl",
      "1 Dose Kichererbsen",
      "1 Dose Kokosmilch",
      "1 Dose gehackte Tomaten",
      "Curry-Gewürzmischung",
      "Kurkuma, Kreuzkümmel",
      "Knoblauch, Ingwer, Zwiebel",
      "Koriander",
    ],
    steps: [
      "Zwiebel, Knoblauch und Ingwer andünsten.",
      "Gewürze zugeben und kurz rösten.",
      "Blumenkohl in Röschen und Tomaten zugeben.",
      "Kokosmilch und Kichererbsen zugeben.",
      "20 Minuten bei mittlerer Hitze köcheln.",
      "Mit frischem Koriander servieren.",
    ],
  },
  {
    id: "d3",
    title: "Zucchini-Lasagne (ohne Nudeln)",
    description: "Klassische Lasagne mit Zucchini-Scheiben statt Pasta – Low-Carb und unwiderstehlich.",
    category: "dinner",
    tags: ["Low-Carb", "High-Protein", "Glutenfrei"],
    prepTime: 45,
    servings: 4,
    emoji: "🥬",
    calories: 340,
    protein: 24,
    ingredients: [
      "3 große Zucchini",
      "250 g Ricotta",
      "400 g Tomatensauce",
      "150 g Mozzarella",
      "2 Eier",
      "Parmesan",
      "Basilikum",
      "Knoblauch",
    ],
    steps: [
      "Zucchini längs in dünne Scheiben schneiden.",
      "Scheiben salzen, 10 Min ziehen lassen, trocknen.",
      "Ricotta mit Eiern, Parmesan und Basilikum mischen.",
      "In einer Auflaufform abwechselnd: Tomatensauce, Zucchini, Ricotta-Mix.",
      "Mit Mozzarella abschließen.",
      "Bei 180°C 35 Minuten backen.",
    ],
  },
  {
    id: "d4",
    title: "Palak Paneer",
    description: "Cremiges indisches Spinatgericht mit gebratenem Paneer – würzig und sättigend.",
    category: "dinner",
    tags: ["Low-Carb", "High-Protein", "Glutenfrei"],
    prepTime: 30,
    servings: 3,
    emoji: "🌿",
    calories: 360,
    protein: 22,
    ingredients: [
      "500 g Blattspinat",
      "250 g Paneer",
      "1 Zwiebel",
      "Tomaten",
      "Knoblauch, Ingwer",
      "Garam Masala, Kreuzkümmel",
      "Sahne oder Kokosmilch",
      "Ghee oder Öl",
    ],
    steps: [
      "Paneer in Würfel schneiden und goldbraun braten, beiseitelegen.",
      "Zwiebel, Knoblauch und Ingwer andünsten.",
      "Gewürze rösten, Tomaten zugeben.",
      "Spinat zugeben und zusammenfallen lassen.",
      "Alles pürieren, Sahne einrühren.",
      "Paneer zurück in die Sauce geben.",
    ],
  },
  {
    id: "d5",
    title: "Blumenkohl-Steak mit Chimichurri",
    description: "Im Ofen gebratenes Blumenkohl-Steak mit einer frischen argentinischen Kräutersauce.",
    category: "dinner",
    tags: ["Low-Carb", "High-Protein", "Vegan", "Glutenfrei"],
    prepTime: 35,
    servings: 2,
    emoji: "🌼",
    calories: 260,
    protein: 9,
    ingredients: [
      "1 großer Blumenkohl",
      "Große Menge Petersilie",
      "Oregano",
      "Knoblauch",
      "Rotweinessig",
      "Olivenöl",
      "Chiliflocken",
      "Meersalz",
    ],
    steps: [
      "Blumenkohl in 2 cm dicke Scheiben schneiden.",
      "Mit Olivenöl bepinseln, salzen.",
      "Bei 220°C 25 Minuten backen (einmal wenden).",
      "Chimichurri: Petersilie, Knoblauch, Essig, Öl und Chili mixen.",
      "Blumenkohl-Steaks mit Chimichurri servieren.",
    ],
  },
  {
    id: "d6",
    title: "Egg-Fried Cauliflower Rice",
    description: "Gebratener Blumenkohl-Reis mit Ei – Low-Carb-Variante des chinesischen Klassikers.",
    category: "dinner",
    tags: ["Low-Carb", "High-Protein", "Glutenfrei"],
    prepTime: 20,
    servings: 2,
    emoji: "🍚",
    calories: 290,
    protein: 20,
    ingredients: [
      "1 Blumenkohl",
      "3 Eier",
      "2 EL Sojasoße",
      "Knoblauch, Ingwer",
      "Frühlingszwiebeln",
      "Erbsen (TK)",
      "Sesamöl",
      "Sesam",
    ],
    steps: [
      "Blumenkohl in Florets teilen und im Mixer grob zerkleinern.",
      "In Sesamöl mit Knoblauch und Ingwer anbraten.",
      "Erbsen zugeben.",
      "Eier verquirlen und in die Pfanne geben, rühren.",
      "Mit Sojasoße würzen.",
      "Mit Frühlingszwiebeln und Sesam servieren.",
    ],
  },
  {
    id: "d7",
    title: "Linsen-Dal mit Spinat",
    description: "Sämiges rotes Linsen-Dal mit frischem Spinat – Soulfood auf indische Art.",
    category: "dinner",
    tags: ["Low-Carb", "High-Protein", "Vegan", "Glutenfrei"],
    prepTime: 30,
    servings: 4,
    emoji: "🫘",
    calories: 310,
    protein: 18,
    ingredients: [
      "200 g rote Linsen",
      "200 g Babyspinat",
      "1 Dose Kokosmilch",
      "Zwiebel, Knoblauch, Ingwer",
      "Kurkuma, Kreuzkümmel, Koriander",
      "Zitronensaft",
      "Koriander frisch",
    ],
    steps: [
      "Linsen abspülen.",
      "Zwiebel, Knoblauch, Ingwer andünsten, Gewürze rösten.",
      "Linsen und Kokosmilch zugeben, 15 Min köcheln.",
      "Spinat unterrühren und zusammenfallen lassen.",
      "Mit Zitronensaft abschmecken.",
      "Mit frischem Koriander servieren.",
    ],
  },
  {
    id: "d8",
    title: "Tempeh-Stir-Fry mit Gemüse",
    description: "Knuspriger Tempeh mit buntem Gemüse in Teriyaki-Sauce – schnell und nährstoffreich.",
    category: "dinner",
    tags: ["Low-Carb", "High-Protein", "Vegan"],
    prepTime: 25,
    servings: 2,
    emoji: "🥢",
    calories: 350,
    protein: 26,
    ingredients: [
      "250 g Tempeh",
      "1 Paprika",
      "200 g Brokkoli",
      "1 Möhre",
      "Teriyaki-Sauce",
      "Ingwer, Knoblauch",
      "Sesamöl",
      "Sesam, Frühlingszwiebeln",
    ],
    steps: [
      "Tempeh in Würfel schneiden und in Sesamöl knusprig braten.",
      "Herausnehmen, Gemüse im gleichen Öl anbraten.",
      "Knoblauch und Ingwer kurz mitbraten.",
      "Tempeh zurück in die Pfanne, Teriyaki-Sauce zugeben.",
      "Alles gut durchschwenken.",
      "Mit Sesam und Frühlingszwiebeln servieren.",
    ],
  },
  {
    id: "d9",
    title: "Gefüllte Paprika mit Linsen",
    description: "Bunte Paprikaschoten prall gefüllt mit gewürzten roten Linsen und Feta.",
    category: "dinner",
    tags: ["Low-Carb", "High-Protein", "Glutenfrei"],
    prepTime: 40,
    servings: 4,
    emoji: "🫑",
    calories: 290,
    protein: 16,
    ingredients: [
      "4 Paprikaschoten",
      "150 g rote Linsen",
      "100 g Feta",
      "1 Dose gehackte Tomaten",
      "Gewürze (Kreuzkümmel, Paprika)",
      "Zwiebel, Knoblauch",
      "Frische Petersilie",
    ],
    steps: [
      "Linsen kochen und abtropfen lassen.",
      "Zwiebel und Knoblauch andünsten, Tomaten und Gewürze zugeben.",
      "Linsen und Feta untermengen.",
      "Paprikadeckel abschneiden, Kerne entfernen.",
      "Paprika mit Linsenmix füllen.",
      "Bei 200°C 25 Minuten backen.",
    ],
  },
  {
    id: "d10",
    title: "Edamame-Bowl mit Sesam-Dressing",
    description: "Frische Edamame, Gurke und Avocado in einer nussigen Sesam-Ingwer-Marinade.",
    category: "dinner",
    tags: ["Low-Carb", "High-Protein", "Vegan", "Glutenfrei"],
    prepTime: 15,
    servings: 2,
    emoji: "🫛",
    calories: 340,
    protein: 20,
    ingredients: [
      "300 g Edamame (TK, geschält)",
      "1 Gurke",
      "1 Avocado",
      "Sesam",
      "2 EL Tahin",
      "Sojasoße",
      "Ingwer",
      "Limettensaft",
      "Frühlingszwiebeln",
    ],
    steps: [
      "Edamame auftauen.",
      "Gurke in Scheiben schneiden, Avocado würfeln.",
      "Dressing: Tahin, Sojasoße, Ingwer, Limette mixen.",
      "Alles in Schüsseln anrichten.",
      "Dressing darüber gießen.",
      "Mit Sesam und Frühlingszwiebeln toppen.",
    ],
  },
  {
    id: "d11",
    title: "Pilz-Feta-Frittata",
    description: "Ofenfrittata mit würzigen Pilzen, Spinat und Feta – perfekt für den Abend.",
    category: "dinner",
    tags: ["Low-Carb", "High-Protein", "Glutenfrei"],
    prepTime: 30,
    servings: 4,
    emoji: "🍄",
    calories: 310,
    protein: 24,
    ingredients: [
      "6 Eier",
      "300 g gemischte Pilze",
      "100 g Babyspinat",
      "100 g Feta",
      "1 Zwiebel",
      "Thymian",
      "Olivenöl",
    ],
    steps: [
      "Ofen auf 180°C vorheizen.",
      "Pilze und Zwiebel in ofenfester Pfanne andünsten.",
      "Spinat zugeben und zusammenfallen lassen.",
      "Eier verquirlen, Feta hineinbröseln.",
      "Eiermasse über das Gemüse gießen.",
      "10 Min auf dem Herd, dann 15 Min im Ofen fertigbacken.",
    ],
  },
  {
    id: "d12",
    title: "Kichererbsen-Spinat-Curry",
    description: "Schnelles, sättigendes Curry mit knackigen Kichererbsen und cremigem Spinat.",
    category: "dinner",
    tags: ["Low-Carb", "High-Protein", "Vegan", "Glutenfrei"],
    prepTime: 25,
    servings: 3,
    emoji: "🍜",
    calories: 330,
    protein: 17,
    ingredients: [
      "2 Dosen Kichererbsen",
      "300 g Blattspinat",
      "1 Dose Kokosmilch",
      "2 Tomaten",
      "Zwiebel, Knoblauch",
      "Garam Masala, Kurkuma",
      "Chilischote",
    ],
    steps: [
      "Kichererbsen abgießen und kurz anrösten.",
      "Zwiebel, Knoblauch und Chili andünsten.",
      "Tomaten und Gewürze zugeben.",
      "Kokosmilch und Kichererbsen zugeben, 10 Min köcheln.",
      "Spinat unterrühren und erhitzen.",
      "Mit Joghurt oder Koriander servieren.",
    ],
  },
];

export const ALL_RECIPES: Recipe[] = [...LUNCH_RECIPES, ...DINNER_RECIPES];

export function getRecipeById(id: string): Recipe | undefined {
  return ALL_RECIPES.find((r) => r.id === id);
}
